# Generated by Django 4.1.2 on 2022-10-28 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Reviews",
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
