# Generated by Django 4.1.2 on 2022-10-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("home", "0002_delete_reviews_delete_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodPlace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_id", models.CharField(max_length=100)),
                ("business_name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("inspection_type", models.CharField(max_length=100)),
                ("inspection_score", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=100)),
                ("risk_category", models.CharField(max_length=100)),
                ("violation_description", models.TextField()),
            ],
        ),
    ]
